# Generated by Django 4.2 on 2023-04-04 23:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecoCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cream', models.CharField(choices=[('round', 'Round'), ('stripe', 'Stripe'), ('flower', 'Flower')], default='round', max_length=10)),
                ('creamcolor', colorfield.fields.ColorField(default='#ffffff', help_text='원하는 색상을 선택하세요.', image_field=None, max_length=18, samples=None)),
                ('letter', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('circle', 'Circle'), ('square', 'Square'), ('heart', 'Heart')], default='circle', max_length=10)),
                ('color', colorfield.fields.ColorField(default='#ffffff', help_text='원하는 색상을 선택하세요.', image_field=None, max_length=18, samples=None)),
                ('image', models.URLField(blank=True, null=True)),
                ('lettering', models.CharField(default='Happy Birthday', max_length=30)),
            ],
        ),
    ]
