# Generated by Django 4.2 on 2023-04-04 16:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cream', models.CharField(choices=[('flower', 'Flower'), ('wave', 'Wave'), ('round', 'Round')], default='', max_length=20)),
                ('topping', models.CharField(choices=[('ribbon', 'Ribbon'), ('sprinkles', 'Sprinkles'), ('color', 'Color'), ('cherry', 'Cherry'), ('sparkles', 'Sparkles'), ('heart', 'Heart'), ('cream', 'Cream')], default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Topping',
                'verbose_name_plural': 'Toppings',
            },
        ),
        migrations.CreateModel(
            name='UserCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#ffffff', help_text='원하는 색상을 선택하세요.', image_field=None, max_length=18, samples=None)),
                ('image', models.URLField(blank=True, null=True)),
                ('lettering', models.CharField(default='Happy Birthday', max_length=30)),
            ],
        ),
    ]
