# Generated by Django 4.2 on 2023-04-04 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercakes', to=settings.AUTH_USER_MODEL),
        ),
    ]
