# Generated by Django 4.2 on 2023-04-05 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitors', '0001_initial'),
        ('cake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercake',
            name='visitor',
            field=models.ManyToManyField(related_name='usercakes', to='visitors.visitor'),
        ),
        migrations.AddField(
            model_name='decocake',
            name='usercake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decocakes', to='cake.usercake'),
        ),
        migrations.AddField(
            model_name='decocake',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decocakes', to='visitors.visitor'),
        ),
    ]
