# Generated by Django 4.2 on 2023-04-04 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
        ('cake', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercake',
            old_name='visitors',
            new_name='visitor',
        ),
        migrations.RemoveField(
            model_name='decocake',
            name='visitors',
        ),
        migrations.AddField(
            model_name='decocake',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decocakes', to='visitors.visitor'),
        ),
    ]
