# Generated by Django 4.2 on 2023-04-06 02:16

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=7)),
                ('cakeshape', models.CharField(choices=[('circle', 'Circle'), ('square', 'Square'), ('heart', 'Heart')], default='circle', max_length=10)),
                ('cakecolor', colorfield.fields.ColorField(default='#ffffff', help_text='원하는 색상을 선택하세요.', image_field=None, max_length=18, samples=None)),
                ('cream', models.CharField(choices=[('round', 'Round'), ('stripe', 'Stripe'), ('flower', 'Flower')], default='round', max_length=10)),
                ('creamcolor', colorfield.fields.ColorField(default='#ffffff', help_text='원하는 색상을 선택하세요.', image_field=None, max_length=18, samples=None)),
                ('image', models.URLField(blank=True, null=True)),
                ('lettering', models.CharField(default='Happy Birthday', help_text='케이크 위에 쓰여질 글자를 입력하세요.', max_length=30)),
                ('letter', models.TextField(blank=True, max_length=50, null=True)),
                ('visitor_name', models.CharField(blank=True, max_length=7, null=True)),
                ('visitor_password', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecoCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(choices=[('strawberry', 'Strawberry'), ('cherry', 'Cherry'), ('sparkle', 'Sparkle'), ('heart', 'Heart'), ('pearl', 'Pearl'), ('ribbon', 'Ribbon')], default='strawberry', max_length=20)),
                ('letter', models.TextField(help_text='생일 축하 메세지를 입력하세요.', max_length=50)),
                ('visitor_name', models.CharField(help_text='방문자의 이름을 입력하세요.', max_length=7)),
                ('visitor_password', models.CharField(help_text='비밀번호는 4자리 숫자로 이루어져야합니다.', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', '비밀번호는 4자리 숫자로 이루어져야합니다.')])),
                ('usercake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decocakes', to='cakes.cakebase')),
            ],
        ),
    ]
