# Generated by Django 4.2 on 2023-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakebase',
            name='visitor_name',
        ),
        migrations.RemoveField(
            model_name='cakebase',
            name='visitor_password',
        ),
        migrations.AddField(
            model_name='cakebase',
            name='letter_count',
            field=models.ManyToManyField(blank=True, related_name='cakebases', to='cakes.decocake'),
        ),
    ]
