# Generated by Django 4.2 on 2023-04-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_remove_cakebase_visitor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakebase',
            name='letter_count',
        ),
    ]
