# Generated by Django 4.2 on 2023-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_remove_cakebase_letter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakebase',
            name='letter_count',
            field=models.ManyToManyField(blank=True, related_name='cakebases', to='cakes.decocake'),
        ),
    ]
