# Generated by Django 4.2 on 2023-04-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_cakebase_letter_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakebase',
            name='letter_count',
        ),
    ]
