# Generated by Django 4.2 on 2023-04-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_remove_cakebase_letter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakebase',
            name='visitor_name',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='cakebase',
            name='visitor_password',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
