# Generated by Django 4.2 on 2023-04-04 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=7)),
                ('password', models.CharField(help_text='비밀번호는 4자리 숫자로 이루어져야합니다.', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', '비밀번호는 4자리 숫자로 이루어져야합니다.')])),
            ],
        ),
    ]
